// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'persistence/entities/activity.dart';
import 'persistence/entities/biome.dart';
import 'persistence/entities/character_component_option.dart';
import 'persistence/entities/child_profile.dart';
import 'persistence/entities/difficulty_model.dart';
import 'persistence/entities/pal.dart';
import 'persistence/entities/pal_attribute.dart';
import 'persistence/entities/parent_settings_entry.dart';
import 'persistence/entities/screen_time_entry.dart';
import 'persistence/entities/skill_level.dart';
import 'persistence/entities/sprite_asset.dart';
import 'persistence/entities/sprite_component_selection.dart';
import 'persistence/entities/task_record.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 7734208788023056508),
    name: 'Activity',
    lastPropertyId: const obx_int.IdUid(7, 1343719411388336974),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1525099769235044556),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6624351320925073687),
        name: 'palId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(1, 7449762444375996414),
        relationField: 'pal',
        relationTarget: 'Pal',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4522769392280205418),
        name: 'biomeId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(2, 4858676440940217573),
        relationField: 'biome',
        relationTarget: 'Biome',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3620761214242845990),
        name: 'activityType',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6609822434187438406),
        name: 'requiredTaskCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 5674312575791569581),
        name: 'startedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 1343719411388336974),
        name: 'completedAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'taskRecords',
        srcEntity: 'TaskRecord',
        srcField: 'activity',
      ),
    ],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 8307711397431201546),
    name: 'Biome',
    lastPropertyId: const obx_int.IdUid(5, 9142547070335590303),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2265002581159970669),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1710860998258899210),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7325763580233579735),
        name: 'difficultyTier',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1039622362481131133),
        name: 'themeAssetPath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 9142547070335590303),
        name: 'unlockMinPalLevel',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 4291946369222925878),
    name: 'CharacterComponentOption',
    lastPropertyId: const obx_int.IdUid(5, 7827452296643946539),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 9023457009095329285),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 9056434488793502133),
        name: 'componentSlot',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8744355749486827226),
        name: 'assetPath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5460950411714507154),
        name: 'displayLabel',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7827452296643946539),
        name: 'guidedModeEligible',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 6019702157470948388),
    name: 'ChildProfile',
    lastPropertyId: const obx_int.IdUid(4, 3876015296276290039),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5794706775170536016),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1694040832008560113),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7025556374606001087),
        name: 'ageYears',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3876015296276290039),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 1264027403658526936),
    name: 'DifficultyModel',
    lastPropertyId: const obx_int.IdUid(1, 4030664870033804912),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4030664870033804912),
        name: 'id',
        type: 6,
        flags: 1,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'skillLevels',
        srcEntity: 'SkillLevel',
        srcField: 'difficultyModel',
      ),
    ],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(6, 4179212821778405790),
    name: 'Pal',
    lastPropertyId: const obx_int.IdUid(15, 3549472387839902912),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5542254175442528106),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5747020338560513217),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7646371396628007737),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3159361516157622928),
        name: 'lastInteractionAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 754122743981738817),
        name: 'hunger',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 3972092090067592359),
        name: 'mood',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 3692903958384448433),
        name: 'energy',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 1787360260878830157),
        name: 'isActive',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 6561986787892472886),
        name: 'archivedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 1173341804761915090),
        name: 'isFrozen',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 4732427964739077654),
        name: 'frozenSince',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 5344588331569435667),
        name: 'spriteAssetId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(3, 3832135242332755946),
        relationField: 'spriteAsset',
        relationTarget: 'SpriteAsset',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 3657858489545352813),
        name: 'difficultyModelId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(4, 875184269714988999),
        relationField: 'difficultyModel',
        relationTarget: 'DifficultyModel',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 1733356565500335286),
        name: 'locationState',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 3549472387839902912),
        name: 'currentBiomeId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(5, 447459880048974375),
        relationField: 'currentBiome',
        relationTarget: 'Biome',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'taskHistory',
        srcEntity: 'TaskRecord',
        srcField: 'pal',
      ),
      obx_int.ModelBacklink(
        name: 'activityHistory',
        srcEntity: 'Activity',
        srcField: 'pal',
      ),
      obx_int.ModelBacklink(
        name: 'attributes',
        srcEntity: 'PalAttribute',
        srcField: 'pal',
      ),
    ],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(7, 8080747406461047558),
    name: 'SkillLevel',
    lastPropertyId: const obx_int.IdUid(5, 292343247578410394),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8146400066441507087),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2739460896140354084),
        name: 'difficultyModelId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(6, 2993160447763185430),
        relationField: 'difficultyModel',
        relationTarget: 'DifficultyModel',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6666093571104881414),
        name: 'categoryKey',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6095339648498474076),
        name: 'level',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 292343247578410394),
        name: 'lastLevelUpAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(8, 2752074059510668181),
    name: 'SpriteAsset',
    lastPropertyId: const obx_int.IdUid(10, 6558184812077331101),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7488399701122595951),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8561440020856066248),
        name: 'spriteFilePath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7558131177587313614),
        name: 'paletteId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4038475631684277271),
        name: 'spriteWidth',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 4685101073906992897),
        name: 'spriteHeight',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1279103098554040411),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 6860768634675849102),
        name: 'segmentationModel',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 5345154597662272323),
        name: 'segmentationConfidence',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 7932157209445529918),
        name: 'sourceType',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 6558184812077331101),
        name: 'designMode',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(9, 558528727196972903),
    name: 'SpriteComponentSelection',
    lastPropertyId: const obx_int.IdUid(3, 4396008692385035904),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6685239594953568963),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5189224135206880562),
        name: 'spriteAssetId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(7, 8351347029752771951),
        relationField: 'spriteAsset',
        relationTarget: 'SpriteAsset',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4396008692385035904),
        name: 'componentOptionId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(8, 5601664328128034121),
        relationField: 'componentOption',
        relationTarget: 'CharacterComponentOption',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(10, 1843339178997570490),
    name: 'TaskRecord',
    lastPropertyId: const obx_int.IdUid(9, 6817240668352815678),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1749523667806916204),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1206231850061561317),
        name: 'palId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(9, 5456433217014248580),
        relationField: 'pal',
        relationTarget: 'Pal',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2474459044241857603),
        name: 'activityId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(10, 7593485018642480854),
        relationField: 'activity',
        relationTarget: 'Activity',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5212468044803427184),
        name: 'categoryKey',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 1860431421669985993),
        name: 'difficultyAtTime',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4757688160590417940),
        name: 'wasCorrect',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 8252406686792392069),
        name: 'responseTimeMs',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 266348637081871740),
        name: 'completedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 6817240668352815678),
        name: 'presentationMode',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(11, 4963445883784610866),
    name: 'PalAttribute',
    lastPropertyId: const obx_int.IdUid(4, 3209172299817971789),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 257816987845777243),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8064878840275715894),
        name: 'palId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(11, 1767262495331150781),
        relationField: 'pal',
        relationTarget: 'Pal',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7358309991486661779),
        name: 'key',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3209172299817971789),
        name: 'value',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(12, 1237693884234384724),
    name: 'ParentSettingsEntry',
    lastPropertyId: const obx_int.IdUid(3, 6148848013871311134),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6406379324062481190),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6619083375521315596),
        name: 'tirednessThresholdMinutes',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6148848013871311134),
        name: 'isTirednessLimitEnabled',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(13, 1376588481007802239),
    name: 'ScreenTimeEntry',
    lastPropertyId: const obx_int.IdUid(3, 1119040233068233811),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1056022356145588862),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7118419157120317027),
        name: 'activeScreenTimeSeconds',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1119040233068233811),
        name: 'lastResetDate',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(13, 1376588481007802239),
    lastIndexId: const obx_int.IdUid(11, 1767262495331150781),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    Activity: obx_int.EntityDefinition<Activity>(
      model: _entities[0],
      toOneRelations: (Activity object) => [object.pal, object.biome],
      toManyRelations: (Activity object) => {
        obx_int.RelInfo<TaskRecord>.toOneBacklink(
          3,
          object.id,
          (TaskRecord srcObject) => srcObject.activity,
        ): object.taskRecords,
      },
      getId: (Activity object) => object.id,
      setId: (Activity object, int id) {
        object.id = id;
      },
      objectToFB: (Activity object, fb.Builder fbb) {
        final activityTypeOffset = fbb.writeString(object.activityType);
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.pal.targetId);
        fbb.addInt64(2, object.biome.targetId);
        fbb.addOffset(3, activityTypeOffset);
        fbb.addInt64(4, object.requiredTaskCount);
        fbb.addInt64(5, object.startedAt.millisecondsSinceEpoch);
        fbb.addInt64(6, object.completedAt?.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final completedAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          16,
        );
        final object = Activity()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..activityType = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 10, '')
          ..requiredTaskCount = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            12,
            0,
          )
          ..startedAt = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0),
          )
          ..completedAt = completedAtValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(completedAtValue);
        object.pal.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        object.pal.attach(store);
        object.biome.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        object.biome.attach(store);
        obx_int.InternalToManyAccess.setRelInfo<Activity>(
          object.taskRecords,
          store,
          obx_int.RelInfo<TaskRecord>.toOneBacklink(
            3,
            object.id,
            (TaskRecord srcObject) => srcObject.activity,
          ),
        );
        return object;
      },
    ),
    Biome: obx_int.EntityDefinition<Biome>(
      model: _entities[1],
      toOneRelations: (Biome object) => [],
      toManyRelations: (Biome object) => {},
      getId: (Biome object) => object.id,
      setId: (Biome object, int id) {
        object.id = id;
      },
      objectToFB: (Biome object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final themeAssetPathOffset = fbb.writeString(object.themeAssetPath);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addInt64(2, object.difficultyTier);
        fbb.addOffset(3, themeAssetPathOffset);
        fbb.addInt64(4, object.unlockMinPalLevel);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = Biome()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..name = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '')
          ..difficultyTier = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            8,
            0,
          )
          ..themeAssetPath = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 10, '')
          ..unlockMinPalLevel = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            12,
            0,
          );

        return object;
      },
    ),
    CharacterComponentOption:
        obx_int.EntityDefinition<CharacterComponentOption>(
          model: _entities[2],
          toOneRelations: (CharacterComponentOption object) => [],
          toManyRelations: (CharacterComponentOption object) => {},
          getId: (CharacterComponentOption object) => object.id,
          setId: (CharacterComponentOption object, int id) {
            object.id = id;
          },
          objectToFB: (CharacterComponentOption object, fb.Builder fbb) {
            final componentSlotOffset = fbb.writeString(object.componentSlot);
            final assetPathOffset = fbb.writeString(object.assetPath);
            final displayLabelOffset = fbb.writeString(object.displayLabel);
            fbb.startTable(6);
            fbb.addInt64(0, object.id);
            fbb.addOffset(1, componentSlotOffset);
            fbb.addOffset(2, assetPathOffset);
            fbb.addOffset(3, displayLabelOffset);
            fbb.addBool(4, object.guidedModeEligible);
            fbb.finish(fbb.endTable());
            return object.id;
          },
          objectFromFB: (obx.Store store, ByteData fbData) {
            final buffer = fb.BufferContext(fbData);
            final rootOffset = buffer.derefObject(0);

            final object = CharacterComponentOption()
              ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
              ..componentSlot = const fb.StringReader(
                asciiOptimization: true,
              ).vTableGet(buffer, rootOffset, 6, '')
              ..assetPath = const fb.StringReader(
                asciiOptimization: true,
              ).vTableGet(buffer, rootOffset, 8, '')
              ..displayLabel = const fb.StringReader(
                asciiOptimization: true,
              ).vTableGet(buffer, rootOffset, 10, '')
              ..guidedModeEligible = const fb.BoolReader().vTableGet(
                buffer,
                rootOffset,
                12,
                false,
              );

            return object;
          },
        ),
    ChildProfile: obx_int.EntityDefinition<ChildProfile>(
      model: _entities[3],
      toOneRelations: (ChildProfile object) => [],
      toManyRelations: (ChildProfile object) => {},
      getId: (ChildProfile object) => object.id,
      setId: (ChildProfile object, int id) {
        object.id = id;
      },
      objectToFB: (ChildProfile object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addInt64(2, object.ageYears);
        fbb.addInt64(3, object.createdAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = ChildProfile()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..name = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '')
          ..ageYears = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            8,
            0,
          )
          ..createdAt = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
          );

        return object;
      },
    ),
    DifficultyModel: obx_int.EntityDefinition<DifficultyModel>(
      model: _entities[4],
      toOneRelations: (DifficultyModel object) => [],
      toManyRelations: (DifficultyModel object) => {
        obx_int.RelInfo<SkillLevel>.toOneBacklink(
          2,
          object.id,
          (SkillLevel srcObject) => srcObject.difficultyModel,
        ): object.skillLevels,
      },
      getId: (DifficultyModel object) => object.id,
      setId: (DifficultyModel object, int id) {
        object.id = id;
      },
      objectToFB: (DifficultyModel object, fb.Builder fbb) {
        fbb.startTable(2);
        fbb.addInt64(0, object.id);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = DifficultyModel()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        obx_int.InternalToManyAccess.setRelInfo<DifficultyModel>(
          object.skillLevels,
          store,
          obx_int.RelInfo<SkillLevel>.toOneBacklink(
            2,
            object.id,
            (SkillLevel srcObject) => srcObject.difficultyModel,
          ),
        );
        return object;
      },
    ),
    Pal: obx_int.EntityDefinition<Pal>(
      model: _entities[5],
      toOneRelations: (Pal object) => [
        object.spriteAsset,
        object.difficultyModel,
        object.currentBiome,
      ],
      toManyRelations: (Pal object) => {
        obx_int.RelInfo<TaskRecord>.toOneBacklink(
          2,
          object.id,
          (TaskRecord srcObject) => srcObject.pal,
        ): object.taskHistory,
        obx_int.RelInfo<Activity>.toOneBacklink(
          2,
          object.id,
          (Activity srcObject) => srcObject.pal,
        ): object.activityHistory,
        obx_int.RelInfo<PalAttribute>.toOneBacklink(
          2,
          object.id,
          (PalAttribute srcObject) => srcObject.pal,
        ): object.attributes,
      },
      getId: (Pal object) => object.id,
      setId: (Pal object, int id) {
        object.id = id;
      },
      objectToFB: (Pal object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final locationStateOffset = fbb.writeString(object.locationState);
        fbb.startTable(16);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addInt64(2, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(3, object.lastInteractionAt.millisecondsSinceEpoch);
        fbb.addFloat64(4, object.hunger);
        fbb.addFloat64(5, object.mood);
        fbb.addFloat64(6, object.energy);
        fbb.addBool(7, object.isActive);
        fbb.addInt64(8, object.archivedAt?.millisecondsSinceEpoch);
        fbb.addBool(9, object.isFrozen);
        fbb.addInt64(10, object.frozenSince?.millisecondsSinceEpoch);
        fbb.addInt64(11, object.spriteAsset.targetId);
        fbb.addInt64(12, object.difficultyModel.targetId);
        fbb.addOffset(13, locationStateOffset);
        fbb.addInt64(14, object.currentBiome.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final archivedAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          20,
        );
        final frozenSinceValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          24,
        );
        final object = Pal()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..name = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '')
          ..createdAt = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0),
          )
          ..lastInteractionAt = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
          )
          ..hunger = const fb.Float64Reader().vTableGet(
            buffer,
            rootOffset,
            12,
            0,
          )
          ..mood = const fb.Float64Reader().vTableGet(buffer, rootOffset, 14, 0)
          ..energy = const fb.Float64Reader().vTableGet(
            buffer,
            rootOffset,
            16,
            0,
          )
          ..isActive = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            18,
            false,
          )
          ..archivedAt = archivedAtValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(archivedAtValue)
          ..isFrozen = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            22,
            false,
          )
          ..frozenSince = frozenSinceValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(frozenSinceValue)
          ..locationState = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 30, '');
        object.spriteAsset.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          26,
          0,
        );
        object.spriteAsset.attach(store);
        object.difficultyModel.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          28,
          0,
        );
        object.difficultyModel.attach(store);
        object.currentBiome.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          32,
          0,
        );
        object.currentBiome.attach(store);
        obx_int.InternalToManyAccess.setRelInfo<Pal>(
          object.taskHistory,
          store,
          obx_int.RelInfo<TaskRecord>.toOneBacklink(
            2,
            object.id,
            (TaskRecord srcObject) => srcObject.pal,
          ),
        );
        obx_int.InternalToManyAccess.setRelInfo<Pal>(
          object.activityHistory,
          store,
          obx_int.RelInfo<Activity>.toOneBacklink(
            2,
            object.id,
            (Activity srcObject) => srcObject.pal,
          ),
        );
        obx_int.InternalToManyAccess.setRelInfo<Pal>(
          object.attributes,
          store,
          obx_int.RelInfo<PalAttribute>.toOneBacklink(
            2,
            object.id,
            (PalAttribute srcObject) => srcObject.pal,
          ),
        );
        return object;
      },
    ),
    SkillLevel: obx_int.EntityDefinition<SkillLevel>(
      model: _entities[6],
      toOneRelations: (SkillLevel object) => [object.difficultyModel],
      toManyRelations: (SkillLevel object) => {},
      getId: (SkillLevel object) => object.id,
      setId: (SkillLevel object, int id) {
        object.id = id;
      },
      objectToFB: (SkillLevel object, fb.Builder fbb) {
        final categoryKeyOffset = fbb.writeString(object.categoryKey);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.difficultyModel.targetId);
        fbb.addOffset(2, categoryKeyOffset);
        fbb.addInt64(3, object.level);
        fbb.addInt64(4, object.lastLevelUpAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = SkillLevel()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..categoryKey = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 8, '')
          ..level = const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0)
          ..lastLevelUpAt = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
          );
        object.difficultyModel.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        object.difficultyModel.attach(store);
        return object;
      },
    ),
    SpriteAsset: obx_int.EntityDefinition<SpriteAsset>(
      model: _entities[7],
      toOneRelations: (SpriteAsset object) => [],
      toManyRelations: (SpriteAsset object) => {},
      getId: (SpriteAsset object) => object.id,
      setId: (SpriteAsset object, int id) {
        object.id = id;
      },
      objectToFB: (SpriteAsset object, fb.Builder fbb) {
        final spriteFilePathOffset = fbb.writeString(object.spriteFilePath);
        final paletteIdOffset = fbb.writeString(object.paletteId);
        final segmentationModelOffset = fbb.writeString(
          object.segmentationModel,
        );
        final sourceTypeOffset = fbb.writeString(object.sourceType);
        final designModeOffset = fbb.writeString(object.designMode);
        fbb.startTable(11);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, spriteFilePathOffset);
        fbb.addOffset(2, paletteIdOffset);
        fbb.addInt64(3, object.spriteWidth);
        fbb.addInt64(4, object.spriteHeight);
        fbb.addInt64(5, object.createdAt.millisecondsSinceEpoch);
        fbb.addOffset(6, segmentationModelOffset);
        fbb.addFloat64(7, object.segmentationConfidence);
        fbb.addOffset(8, sourceTypeOffset);
        fbb.addOffset(9, designModeOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = SpriteAsset()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..spriteFilePath = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '')
          ..paletteId = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 8, '')
          ..spriteWidth = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            10,
            0,
          )
          ..spriteHeight = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            12,
            0,
          )
          ..createdAt = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0),
          )
          ..segmentationModel = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 16, '')
          ..segmentationConfidence = const fb.Float64Reader().vTableGet(
            buffer,
            rootOffset,
            18,
            0,
          )
          ..sourceType = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 20, '')
          ..designMode = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 22, '');

        return object;
      },
    ),
    SpriteComponentSelection:
        obx_int.EntityDefinition<SpriteComponentSelection>(
          model: _entities[8],
          toOneRelations: (SpriteComponentSelection object) => [
            object.spriteAsset,
            object.componentOption,
          ],
          toManyRelations: (SpriteComponentSelection object) => {},
          getId: (SpriteComponentSelection object) => object.id,
          setId: (SpriteComponentSelection object, int id) {
            object.id = id;
          },
          objectToFB: (SpriteComponentSelection object, fb.Builder fbb) {
            fbb.startTable(4);
            fbb.addInt64(0, object.id);
            fbb.addInt64(1, object.spriteAsset.targetId);
            fbb.addInt64(2, object.componentOption.targetId);
            fbb.finish(fbb.endTable());
            return object.id;
          },
          objectFromFB: (obx.Store store, ByteData fbData) {
            final buffer = fb.BufferContext(fbData);
            final rootOffset = buffer.derefObject(0);

            final object = SpriteComponentSelection()
              ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
            object.spriteAsset.targetId = const fb.Int64Reader().vTableGet(
              buffer,
              rootOffset,
              6,
              0,
            );
            object.spriteAsset.attach(store);
            object.componentOption.targetId = const fb.Int64Reader().vTableGet(
              buffer,
              rootOffset,
              8,
              0,
            );
            object.componentOption.attach(store);
            return object;
          },
        ),
    TaskRecord: obx_int.EntityDefinition<TaskRecord>(
      model: _entities[9],
      toOneRelations: (TaskRecord object) => [object.pal, object.activity],
      toManyRelations: (TaskRecord object) => {},
      getId: (TaskRecord object) => object.id,
      setId: (TaskRecord object, int id) {
        object.id = id;
      },
      objectToFB: (TaskRecord object, fb.Builder fbb) {
        final categoryKeyOffset = fbb.writeString(object.categoryKey);
        final presentationModeOffset = fbb.writeString(object.presentationMode);
        fbb.startTable(10);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.pal.targetId);
        fbb.addInt64(2, object.activity.targetId);
        fbb.addOffset(3, categoryKeyOffset);
        fbb.addInt64(4, object.difficultyAtTime);
        fbb.addBool(5, object.wasCorrect);
        fbb.addInt64(6, object.responseTimeMs);
        fbb.addInt64(7, object.completedAt.millisecondsSinceEpoch);
        fbb.addOffset(8, presentationModeOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = TaskRecord()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..categoryKey = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 10, '')
          ..difficultyAtTime = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            12,
            0,
          )
          ..wasCorrect = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            14,
            false,
          )
          ..responseTimeMs = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            16,
            0,
          )
          ..completedAt = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0),
          )
          ..presentationMode = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 20, '');
        object.pal.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        object.pal.attach(store);
        object.activity.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        object.activity.attach(store);
        return object;
      },
    ),
    PalAttribute: obx_int.EntityDefinition<PalAttribute>(
      model: _entities[10],
      toOneRelations: (PalAttribute object) => [object.pal],
      toManyRelations: (PalAttribute object) => {},
      getId: (PalAttribute object) => object.id,
      setId: (PalAttribute object, int id) {
        object.id = id;
      },
      objectToFB: (PalAttribute object, fb.Builder fbb) {
        final keyOffset = fbb.writeString(object.key);
        final valueOffset = fbb.writeString(object.value);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.pal.targetId);
        fbb.addOffset(2, keyOffset);
        fbb.addOffset(3, valueOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = PalAttribute()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..key = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 8, '')
          ..value = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 10, '');
        object.pal.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        object.pal.attach(store);
        return object;
      },
    ),
    ParentSettingsEntry: obx_int.EntityDefinition<ParentSettingsEntry>(
      model: _entities[11],
      toOneRelations: (ParentSettingsEntry object) => [],
      toManyRelations: (ParentSettingsEntry object) => {},
      getId: (ParentSettingsEntry object) => object.id,
      setId: (ParentSettingsEntry object, int id) {
        object.id = id;
      },
      objectToFB: (ParentSettingsEntry object, fb.Builder fbb) {
        fbb.startTable(4);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.tirednessThresholdMinutes);
        fbb.addBool(2, object.isTirednessLimitEnabled);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = ParentSettingsEntry()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..tirednessThresholdMinutes = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            6,
            0,
          )
          ..isTirednessLimitEnabled = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            8,
            false,
          );

        return object;
      },
    ),
    ScreenTimeEntry: obx_int.EntityDefinition<ScreenTimeEntry>(
      model: _entities[12],
      toOneRelations: (ScreenTimeEntry object) => [],
      toManyRelations: (ScreenTimeEntry object) => {},
      getId: (ScreenTimeEntry object) => object.id,
      setId: (ScreenTimeEntry object, int id) {
        object.id = id;
      },
      objectToFB: (ScreenTimeEntry object, fb.Builder fbb) {
        fbb.startTable(4);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.activeScreenTimeSeconds);
        fbb.addInt64(2, object.lastResetDate.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = ScreenTimeEntry()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..activeScreenTimeSeconds = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            6,
            0,
          )
          ..lastResetDate = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0),
          );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Activity] entity fields to define ObjectBox queries.
class Activity_ {
  /// See [Activity.id].
  static final id = obx.QueryIntegerProperty<Activity>(
    _entities[0].properties[0],
  );

  /// See [Activity.pal].
  static final pal = obx.QueryRelationToOne<Activity, Pal>(
    _entities[0].properties[1],
  );

  /// See [Activity.biome].
  static final biome = obx.QueryRelationToOne<Activity, Biome>(
    _entities[0].properties[2],
  );

  /// See [Activity.activityType].
  static final activityType = obx.QueryStringProperty<Activity>(
    _entities[0].properties[3],
  );

  /// See [Activity.requiredTaskCount].
  static final requiredTaskCount = obx.QueryIntegerProperty<Activity>(
    _entities[0].properties[4],
  );

  /// See [Activity.startedAt].
  static final startedAt = obx.QueryDateProperty<Activity>(
    _entities[0].properties[5],
  );

  /// See [Activity.completedAt].
  static final completedAt = obx.QueryDateProperty<Activity>(
    _entities[0].properties[6],
  );

  /// see [Activity.taskRecords]
  static final taskRecords = obx.QueryBacklinkToMany<TaskRecord, Activity>(
    TaskRecord_.activity,
  );
}

/// [Biome] entity fields to define ObjectBox queries.
class Biome_ {
  /// See [Biome.id].
  static final id = obx.QueryIntegerProperty<Biome>(_entities[1].properties[0]);

  /// See [Biome.name].
  static final name = obx.QueryStringProperty<Biome>(
    _entities[1].properties[1],
  );

  /// See [Biome.difficultyTier].
  static final difficultyTier = obx.QueryIntegerProperty<Biome>(
    _entities[1].properties[2],
  );

  /// See [Biome.themeAssetPath].
  static final themeAssetPath = obx.QueryStringProperty<Biome>(
    _entities[1].properties[3],
  );

  /// See [Biome.unlockMinPalLevel].
  static final unlockMinPalLevel = obx.QueryIntegerProperty<Biome>(
    _entities[1].properties[4],
  );
}

/// [CharacterComponentOption] entity fields to define ObjectBox queries.
class CharacterComponentOption_ {
  /// See [CharacterComponentOption.id].
  static final id = obx.QueryIntegerProperty<CharacterComponentOption>(
    _entities[2].properties[0],
  );

  /// See [CharacterComponentOption.componentSlot].
  static final componentSlot =
      obx.QueryStringProperty<CharacterComponentOption>(
        _entities[2].properties[1],
      );

  /// See [CharacterComponentOption.assetPath].
  static final assetPath = obx.QueryStringProperty<CharacterComponentOption>(
    _entities[2].properties[2],
  );

  /// See [CharacterComponentOption.displayLabel].
  static final displayLabel = obx.QueryStringProperty<CharacterComponentOption>(
    _entities[2].properties[3],
  );

  /// See [CharacterComponentOption.guidedModeEligible].
  static final guidedModeEligible =
      obx.QueryBooleanProperty<CharacterComponentOption>(
        _entities[2].properties[4],
      );
}

/// [ChildProfile] entity fields to define ObjectBox queries.
class ChildProfile_ {
  /// See [ChildProfile.id].
  static final id = obx.QueryIntegerProperty<ChildProfile>(
    _entities[3].properties[0],
  );

  /// See [ChildProfile.name].
  static final name = obx.QueryStringProperty<ChildProfile>(
    _entities[3].properties[1],
  );

  /// See [ChildProfile.ageYears].
  static final ageYears = obx.QueryIntegerProperty<ChildProfile>(
    _entities[3].properties[2],
  );

  /// See [ChildProfile.createdAt].
  static final createdAt = obx.QueryDateProperty<ChildProfile>(
    _entities[3].properties[3],
  );
}

/// [DifficultyModel] entity fields to define ObjectBox queries.
class DifficultyModel_ {
  /// See [DifficultyModel.id].
  static final id = obx.QueryIntegerProperty<DifficultyModel>(
    _entities[4].properties[0],
  );

  /// see [DifficultyModel.skillLevels]
  static final skillLevels =
      obx.QueryBacklinkToMany<SkillLevel, DifficultyModel>(
        SkillLevel_.difficultyModel,
      );
}

/// [Pal] entity fields to define ObjectBox queries.
class Pal_ {
  /// See [Pal.id].
  static final id = obx.QueryIntegerProperty<Pal>(_entities[5].properties[0]);

  /// See [Pal.name].
  static final name = obx.QueryStringProperty<Pal>(_entities[5].properties[1]);

  /// See [Pal.createdAt].
  static final createdAt = obx.QueryDateProperty<Pal>(
    _entities[5].properties[2],
  );

  /// See [Pal.lastInteractionAt].
  static final lastInteractionAt = obx.QueryDateProperty<Pal>(
    _entities[5].properties[3],
  );

  /// See [Pal.hunger].
  static final hunger = obx.QueryDoubleProperty<Pal>(
    _entities[5].properties[4],
  );

  /// See [Pal.mood].
  static final mood = obx.QueryDoubleProperty<Pal>(_entities[5].properties[5]);

  /// See [Pal.energy].
  static final energy = obx.QueryDoubleProperty<Pal>(
    _entities[5].properties[6],
  );

  /// See [Pal.isActive].
  static final isActive = obx.QueryBooleanProperty<Pal>(
    _entities[5].properties[7],
  );

  /// See [Pal.archivedAt].
  static final archivedAt = obx.QueryDateProperty<Pal>(
    _entities[5].properties[8],
  );

  /// See [Pal.isFrozen].
  static final isFrozen = obx.QueryBooleanProperty<Pal>(
    _entities[5].properties[9],
  );

  /// See [Pal.frozenSince].
  static final frozenSince = obx.QueryDateProperty<Pal>(
    _entities[5].properties[10],
  );

  /// See [Pal.spriteAsset].
  static final spriteAsset = obx.QueryRelationToOne<Pal, SpriteAsset>(
    _entities[5].properties[11],
  );

  /// See [Pal.difficultyModel].
  static final difficultyModel = obx.QueryRelationToOne<Pal, DifficultyModel>(
    _entities[5].properties[12],
  );

  /// See [Pal.locationState].
  static final locationState = obx.QueryStringProperty<Pal>(
    _entities[5].properties[13],
  );

  /// See [Pal.currentBiome].
  static final currentBiome = obx.QueryRelationToOne<Pal, Biome>(
    _entities[5].properties[14],
  );

  /// see [Pal.taskHistory]
  static final taskHistory = obx.QueryBacklinkToMany<TaskRecord, Pal>(
    TaskRecord_.pal,
  );

  /// see [Pal.activityHistory]
  static final activityHistory = obx.QueryBacklinkToMany<Activity, Pal>(
    Activity_.pal,
  );

  /// see [Pal.attributes]
  static final attributes = obx.QueryBacklinkToMany<PalAttribute, Pal>(
    PalAttribute_.pal,
  );
}

/// [SkillLevel] entity fields to define ObjectBox queries.
class SkillLevel_ {
  /// See [SkillLevel.id].
  static final id = obx.QueryIntegerProperty<SkillLevel>(
    _entities[6].properties[0],
  );

  /// See [SkillLevel.difficultyModel].
  static final difficultyModel =
      obx.QueryRelationToOne<SkillLevel, DifficultyModel>(
        _entities[6].properties[1],
      );

  /// See [SkillLevel.categoryKey].
  static final categoryKey = obx.QueryStringProperty<SkillLevel>(
    _entities[6].properties[2],
  );

  /// See [SkillLevel.level].
  static final level = obx.QueryIntegerProperty<SkillLevel>(
    _entities[6].properties[3],
  );

  /// See [SkillLevel.lastLevelUpAt].
  static final lastLevelUpAt = obx.QueryDateProperty<SkillLevel>(
    _entities[6].properties[4],
  );
}

/// [SpriteAsset] entity fields to define ObjectBox queries.
class SpriteAsset_ {
  /// See [SpriteAsset.id].
  static final id = obx.QueryIntegerProperty<SpriteAsset>(
    _entities[7].properties[0],
  );

  /// See [SpriteAsset.spriteFilePath].
  static final spriteFilePath = obx.QueryStringProperty<SpriteAsset>(
    _entities[7].properties[1],
  );

  /// See [SpriteAsset.paletteId].
  static final paletteId = obx.QueryStringProperty<SpriteAsset>(
    _entities[7].properties[2],
  );

  /// See [SpriteAsset.spriteWidth].
  static final spriteWidth = obx.QueryIntegerProperty<SpriteAsset>(
    _entities[7].properties[3],
  );

  /// See [SpriteAsset.spriteHeight].
  static final spriteHeight = obx.QueryIntegerProperty<SpriteAsset>(
    _entities[7].properties[4],
  );

  /// See [SpriteAsset.createdAt].
  static final createdAt = obx.QueryDateProperty<SpriteAsset>(
    _entities[7].properties[5],
  );

  /// See [SpriteAsset.segmentationModel].
  static final segmentationModel = obx.QueryStringProperty<SpriteAsset>(
    _entities[7].properties[6],
  );

  /// See [SpriteAsset.segmentationConfidence].
  static final segmentationConfidence = obx.QueryDoubleProperty<SpriteAsset>(
    _entities[7].properties[7],
  );

  /// See [SpriteAsset.sourceType].
  static final sourceType = obx.QueryStringProperty<SpriteAsset>(
    _entities[7].properties[8],
  );

  /// See [SpriteAsset.designMode].
  static final designMode = obx.QueryStringProperty<SpriteAsset>(
    _entities[7].properties[9],
  );
}

/// [SpriteComponentSelection] entity fields to define ObjectBox queries.
class SpriteComponentSelection_ {
  /// See [SpriteComponentSelection.id].
  static final id = obx.QueryIntegerProperty<SpriteComponentSelection>(
    _entities[8].properties[0],
  );

  /// See [SpriteComponentSelection.spriteAsset].
  static final spriteAsset =
      obx.QueryRelationToOne<SpriteComponentSelection, SpriteAsset>(
        _entities[8].properties[1],
      );

  /// See [SpriteComponentSelection.componentOption].
  static final componentOption =
      obx.QueryRelationToOne<
        SpriteComponentSelection,
        CharacterComponentOption
      >(_entities[8].properties[2]);
}

/// [TaskRecord] entity fields to define ObjectBox queries.
class TaskRecord_ {
  /// See [TaskRecord.id].
  static final id = obx.QueryIntegerProperty<TaskRecord>(
    _entities[9].properties[0],
  );

  /// See [TaskRecord.pal].
  static final pal = obx.QueryRelationToOne<TaskRecord, Pal>(
    _entities[9].properties[1],
  );

  /// See [TaskRecord.activity].
  static final activity = obx.QueryRelationToOne<TaskRecord, Activity>(
    _entities[9].properties[2],
  );

  /// See [TaskRecord.categoryKey].
  static final categoryKey = obx.QueryStringProperty<TaskRecord>(
    _entities[9].properties[3],
  );

  /// See [TaskRecord.difficultyAtTime].
  static final difficultyAtTime = obx.QueryIntegerProperty<TaskRecord>(
    _entities[9].properties[4],
  );

  /// See [TaskRecord.wasCorrect].
  static final wasCorrect = obx.QueryBooleanProperty<TaskRecord>(
    _entities[9].properties[5],
  );

  /// See [TaskRecord.responseTimeMs].
  static final responseTimeMs = obx.QueryIntegerProperty<TaskRecord>(
    _entities[9].properties[6],
  );

  /// See [TaskRecord.completedAt].
  static final completedAt = obx.QueryDateProperty<TaskRecord>(
    _entities[9].properties[7],
  );

  /// See [TaskRecord.presentationMode].
  static final presentationMode = obx.QueryStringProperty<TaskRecord>(
    _entities[9].properties[8],
  );
}

/// [PalAttribute] entity fields to define ObjectBox queries.
class PalAttribute_ {
  /// See [PalAttribute.id].
  static final id = obx.QueryIntegerProperty<PalAttribute>(
    _entities[10].properties[0],
  );

  /// See [PalAttribute.pal].
  static final pal = obx.QueryRelationToOne<PalAttribute, Pal>(
    _entities[10].properties[1],
  );

  /// See [PalAttribute.key].
  static final key = obx.QueryStringProperty<PalAttribute>(
    _entities[10].properties[2],
  );

  /// See [PalAttribute.value].
  static final value = obx.QueryStringProperty<PalAttribute>(
    _entities[10].properties[3],
  );
}

/// [ParentSettingsEntry] entity fields to define ObjectBox queries.
class ParentSettingsEntry_ {
  /// See [ParentSettingsEntry.id].
  static final id = obx.QueryIntegerProperty<ParentSettingsEntry>(
    _entities[11].properties[0],
  );

  /// See [ParentSettingsEntry.tirednessThresholdMinutes].
  static final tirednessThresholdMinutes =
      obx.QueryIntegerProperty<ParentSettingsEntry>(
        _entities[11].properties[1],
      );

  /// See [ParentSettingsEntry.isTirednessLimitEnabled].
  static final isTirednessLimitEnabled =
      obx.QueryBooleanProperty<ParentSettingsEntry>(
        _entities[11].properties[2],
      );
}

/// [ScreenTimeEntry] entity fields to define ObjectBox queries.
class ScreenTimeEntry_ {
  /// See [ScreenTimeEntry.id].
  static final id = obx.QueryIntegerProperty<ScreenTimeEntry>(
    _entities[12].properties[0],
  );

  /// See [ScreenTimeEntry.activeScreenTimeSeconds].
  static final activeScreenTimeSeconds =
      obx.QueryIntegerProperty<ScreenTimeEntry>(_entities[12].properties[1]);

  /// See [ScreenTimeEntry.lastResetDate].
  static final lastResetDate = obx.QueryDateProperty<ScreenTimeEntry>(
    _entities[12].properties[2],
  );
}
